#!/bin/bash

cd linux/

mkdir -p ./obj/
mkdir -p ./obj/source/
mkdir -p ./dep/
mkdir -p ./dep/source/

DIRS=$(cd ./source/; find -L . -type d)

cd ./obj/source/
mkdir -p $DIRS
cd ../../

cd ./dep/source/
mkdir -p $DIRS
cd ../../

make
